name: cgfp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - scikit-learn
  - polars
  - pip
  - pip:
    - transformers==4.28.0
    - datasets
    - openpyxl
