name: cgfp
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.3.1
  - pytorch-cuda=11.8
  - pip=24.0
  - pip:
    - ipykernel
    - transformers==4.28.0
    - datasets==2.20.0
    - openpyxl==3.1.5
    - wandb==0.17.4
    - numpy==1.26.4
    - pandas==2.2.2
    - polars==1.2.0
    - scikit-learn==1.5.1
    - -e .
