name: cgfp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.8
  - scikit-learn
  - pandas
  - polars
  - pip
  - pip:
    - transformers==4.28.0
    - datasets
    - openpyxl
    - wandb==0.16.6
    - -e .
