# TODO: Maybe I should pull out some of the common mappings like "cut" and include some sort of set membership check
TOKEN_MAP_DICT = {
    ## TYPOS ##
    "whole grain rich  rich": "whole grain rich",
    "orchiette": "orecchiette",
    "campanelli": "campanelle",
    "unsweeted": "unsweetened",
    "peeled & deveined": "peeled and deveined",
    "mangu": "mango",
    "siced": "sliced",
    "apple golden delicious": "apple",
    "apple. Gala": "apple",
    "bicsuit": "biscuit",
    "brussel": "brussels sprout",
    "brussel spout": "brussels sprout",
    "brussel sprout": "brussels sprout",
    "bulghur": "bulgur",
    "cabbabe": "cabbage",
    "collard": "collard greens",
    "collard green": "collard greens",
    "freekah": "freekeh",
    "grean pea": "green pea",
    "grit": "grits",
    "jicima": "jicama",
    "lemon grass": "lemongrass",
    "onio": "onion",
    "pummelo": "pomelo",
    "rasberry": "raspberry",
    "shelll": "shell",
    "stawberry": "strawberry",
    "tamato": "tomato",
    "1 island": "1000 island",
    "alfafa": "alfalfa",
    "brocolini": "broccolini",
    "code": "cod",
    "berry lemonage": "berry lemonade",
    "gryo meat": "gyro meat",
    "patry": "pastry",
    "sweetner": "sweetener",
    "tat soi": "tatsoi",
    "tostado shell": "tostada",
    "chery": "cherry",
    "grean": "green",
    "green chile": "green chili",
    "guajillo chile": "guajillo chili",
    "habenero": "habanero",
    "hambuger": "hamburger",
    "harvarti": "havarti",
    "honey mustard dijon": "honey mustard",
    "iceburg": "iceberg",
    "jonogold": "jonagold",
    "marianra": "marinara",
    "mayonaise": "mayonnaise",
    "mayonaisse": "mayonnaise",
    "mirepoux": "mirepoix",
    "monterey jark": "monterey jack",
    "montery jack": "monterey jack",
    "mozzerella": "mozzarella",
    "peperoncini": "pepperoncini",
    "peppercini": "pepperoncini",
    "powedered": "powdered",
    "raisin brain": "raisin bran",
    "reeses pieces": "reese's pieces",
    "sandwhich": "sandwich",
    "snickerdoogle": "snickerdoodle",
    "springle": "sprinkle",
    "sqare rib": "spare rib",
    "stawberry": "strawberry",
    "sun-dried": "sun dried",
    ## INCONSISTENCIES ##
    "skin-on": "skin on",
    "carrots": "carrot",
    "gluten-free": "gluten free",
    "tail-on": "tail on",
    "tail-off": "tail off",
    "sugar-free": "sugar free",
    "fillet": "filet",
    "fat-free": "fat free",
    "rice crispies": "rice krispies",
    "bread crumb": "breadcrumb",
    "bread stick": "breadstick",
    "brussels sprouts": "brussels sprout",
    "bulgur wheat": "bulgur",
    "cranberries": "cranberry",
    "egg": "eggs",
    "heart of palm": "hearts of palm",
    "peppers": "pepper",
    "vegetables": "vegetable",
    "vetegable": "vegetable",
    "wheat bulgur": "bulgur",
    "yuca": "yucca",
    "beef steak": "beefsteak",
    "corn meal": "cornmeal",
    "cornstarch": "corn starch",
    "egg nog": "eggnog",
    "micro greens": "microgreen",
    "micro green": "microgreen",
    "pimiento": "pimento",
    "preserves": "preserve",
    "spring": "spring mix",
    "tostada shell": "tostada",
    "turnip green": "turnip greens",
    "additive": "additives",
    "chives": "chive",
    "corn puffs": "corn puff",
    "cornish game hen": "cornish hen",
    "cous cous": "couscous",
    "dougnut": "doughnut",
    "florets": "floret",
    "froot loop": "froot loops",
    "fruit loop": "froot loops",
    "fruit loops": "froot loops",
    "frito": "fritos",
    "grannysmith": "granny smith",
    ## COOKED ##
    "au jus": "cooked",
    ## RENAME ##
    "aprium": "pluot",
    "banana pepper": "pepper",
    "blood orange": "orange",
    "bluelake bean": "bean",
    "bouillon": "base",
    "cotton candy": "candy",
    "pig": "pork",
    "romano bean": "bean",
    "pigeon pea": "bean",
    "cracker meal": "breadcrumb",
    "hasu": "lotus root",
    "satsuma": "mandarin",
    "white rice": "rice",
    ## CUT ##
    "sliced": "cut",
    "diced": "cut",
    "chopped": "cut",
    "wedge": "cut",
    "segment": "cut",
    "baby": "cut",
    "julienne": "cut",
    "julienned": "cut",
    "quartered": "cut",
    "cubed": "cut",
    "chunk": "cut",
    "trimmed": "cut",
    "half": "cut",
    "spear": "cut",
    "crinkle cut": "cut",
    "florette": "cut",
    "filet": "cut",
    ## WHOLE GRAIN ##
    "whole wheat": "whole grain rich",
    "whole grain": "whole grain rich",
    "white whole wheat": "whole grain rich",
    ## COOKED ##
    "baked": "cooked",
    "fried": "cooked",
    "roasted": "cooked",
    "parboiled": "cooked",
    "parcooked": "cooked",
    "broiled": "cooked",
    "parbaked": "cooked",
    "broiled": "cooked",
    "parfried": "cooked",
    ## FLAVORED ##
    ## PACKAGING ##
    "bag": "ss",
    ## IN JUICE ##
    "in pear juice": "in juice",
    ## SMOKED ##
    "pecanwood smoked": "smoked",
    ## MIXED VEGGIES ##
    "vegetable blend": "vegetable",  # TODO: maybe we need this in basic type handler
    "vegetable cup": "vegetable",
}
