# TODO: Maybe I should pull out some of the common mappings like "cut" and include some sort of set membership check
TOKEN_MAP_DICT = {
    ## TYPOS ##
    "whole grain rich  rich": "whole grain rich",
    "orchiette": "orecchiette",
    "campanelli": "campanelle",
    "unsweeted": "unsweetened",
    "peeled & deveined": "peeled and deveined",
    "mangu": "mango",
    "siced": "sliced",
    "apple golden delicious": "apple",
    "apple. Gala": "apple",
    "bicsuit": "biscuit",
    "brussel": "brussels sprout",
    "brussel spout": "brussels sprout",
    "brussel sprout": "brussels sprout",
    "bulghur": "bulgur",
    "cabbabe": "cabbage",
    "collard": "collard greens",
    "collard green": "collard greens",
    "freekah": "freekeh",
    "grean pea": "green pea",
    "grit": "grits",
    "jicima": "jicama",
    "lemon grass": "lemongrass",
    "onio": "onion",
    "pummelo": "pomelo",
    "rasberry": "raspberry",
    "shelll": "shell",
    "stawberry": "strawberry",
    "tamato": "tomato",
    ## INCONSISTENCIES ##
    "skin-on": "skin on",
    "carrots": "carrot",
    "gluten-free": "gluten free",
    "tail-on": "tail on",
    "tail-off": "tail off",
    "sugar-free": "sugar free",
    "fillet": "filet",
    "fat-free": "fat free",
    "rice crispies": "rice krispies",
    "bread crumb": "breadcrumb",
    "bread stick": "breadstick",
    "brussels sprouts": "brussels sprout",
    "bulgur wheat": "bulgur",
    "cranberries": "cranberry",
    "egg": "eggs",
    "heart of palm": "hearts of palm",
    "peppers": "pepper",
    "vegetables": "vegetable",
    "vetegable": "vegetable",
    "wheat bulgur": "bulgur",
    "yuca": "yucca",
    ## RENAME ##
    "aprium": "pluot",
    "banana pepper": "pepper",
    "bell pepper": "pepper",
    "blood orange": "orange",
    "bluelake bean": "bean",
    "bouillon": "base",
    "cotton candy": "candy",
    "pig": "pork",
    "romano bean": "bean",
    ## CUT ##
    "sliced": "cut",
    "diced": "cut",
    "chopped": "cut",
    "wedge": "cut",
    "segment": "cut",
    "baby": "cut",
    "julienne": "cut",
    "julienned": "cut",
    "quartered": "cut",
    "cubed": "cut",
    "chunk": "cut",
    "trimmed": "cut",
    "half": "cut",
    "spear": "cut",
    "crinkle cut": "cut",
    ## WHOLE GRAIN ##
    "whole wheat": "whole grain rich",
    "whole grain": "whole grain rich",
    "white whole wheat": "whole grain rich",
    ## COOKED ##
    "baked": "cooked",
    "fried": "cooked",
    "roasted": "cooked",
    "parboiled": "cooked",
    "parcooked": "cooked",
    "broiled": "cooked",
    "parbaked": "cooked",
    "broiled": "cooked",
    "parfried": "cooked",
    ## FLAVORED ##
    ## PACKAGING ##
    "bag": "ss",
    ## IN JUICE ##
    "in pear juice": "in juice",
    ## SMOKED ##
    "pecanwood smoked": "smoked",
    ## MIXED VEGGIES ##
    "vegetable blend": "vegetable",
    "vegetable cup": "vegetable",
}
