GROUP_CATEGORY_VALIDATION = {
    "Produce": ["Fruit", "Vegetables", "Roots & Tubers"],
    "Milk & Dairy": ["Butter", "Cheese", "Milk", "Yogurt", "Milk & Dairy"],
    "Meat": [
        "Beef",
        "Chicken",
        "Eggs",
        "Pork",
        "Turkey, Other Poultry",
        "Meat",
    ],  # "Meat" is used for other items without a category like bison, lamb, venison, rabbit, etc.
    "Seafood": [
        "Fish (Farm-Raised)",
        "Fish (Wild)",
        "Seafood",
    ],  # "Seafood" is used for fish that are unconfirmed farm-raised or wild, shellfish, crab, mollusks, scallops, clams, shrimp, etc.
    "Bread, Grains & Legumes": [
        "Grain Products",
        "Legumes",
        "Rice",
        "Tree Nuts & Seeds",
        "Bread, Grains & Legumes",
    ],  # "Bread, Grains & Legumes" is used to account for items not belonging to the other categories
    "Beverages": ["Beverages"],
    "Meals": [
        "Meals"
    ],  # TODO: Figure out how to set something up for primary food product category here
    "Condiments & Snacks": ["Condiments & Snacks"],
}

MISC_COLUMN_TAGS = {
    "All": {
        "Flavor/Cut": {"flavored"},
        "Shape": {"concentrate", "cut", "ground", "jerky"},
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": {"battered", "breaded", "dried"},
        "Cooked/Cleaned": {"cooked"},
        "WG/WGR": {"whole grain rich"},
        "Dietary Concern": {
            "fat free",
            "low fat",
            "low sodium",
            "nonfat",
            "reduced fat",
            "reduced sodium",
            "reduced sugar",
            "salted",
            "unsalted",
        },
        "Additives": {"additives", "no additives", "sweetened"},
        "Dietary Accommodation": {
            "gluten free",
            "halal",
            "kosher",
            "vegan",
            "vegetarian",
        },
        "Frozen": {"frozen"},
        "Packaging": {"canned", "jarred", "pouch", "ss"},
        "Commodity": {"commodity"},
    },
    "Meat": {
        "Flavor/Cut": {
            "brisket",
            "breast",
            "loin",
            "shank",
            "skirt",
            "steak",
            "short rib",
            "t-bone",
            "thigh",
            "wing",
            "ham",
        },
        "Shape": {
            "bacon",
            "chunk",
            "diced",
            "hot dog",
            "meatball",
            "nugget",
            "pepperoni",
            "patty",
            "salami",
            "crumble",
        },
        "Skin": set(),
        "Seed/Bone": {"bone-in"},
        "Processing": {"corned"},
        "Cooked/Cleaned": {"smoked"},
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
    "Seafood": {
        "Flavor/Cut": set(),
        "Shape": set(),
        "Skin": {"tail on", "shell on"},
        "Seed/Bone": {"bone-in"},
        "Processing": set(),
        "Cooked/Cleaned": {"smoked"},
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
    "Fruit": {"Seed/Bone": {"pitted"}},
    "Condiments & Snacks": {
        "Seed/Bone": {"pitted"},
        "Dietary Accommodation": {"non-dairy"},
    },
    "Beverages": {
        "Dietary Concern": {"decaffeinated", "diet", "caffeinated"},
        "Frozen": {"iced"},
    },
}
