"""Defines basic type mappings for specific tokens in CGFP tagging system"""

from cgfp.constants.tokens.tag_sets import NUTS

BASIC_TYPE_MAP = {
    "sea salt": {"Basic Type": "salt"},
    "almond": {"Basic Type": "nut", "Sub-Types": "almond"},
    "baba ganoush": {"Basic Type": "spread", "Sub-Types": "baba ganoush"},
    "baklava": {"Basic Type": "pastry", "Sub-Types": "baklava"},
    "banana bread": {"Basic Type": "bread", "Sub-Types": "banana"},
    "barbacoa": {"Basic Type": "beef", "Sub-Types": "barbacoa"},
    "basil": {"Basic Type": "herb", "Sub-Types": "basil"},
    "bell pepper": {"Basic Type": "pepper", "Sub-Types": "bell"},
    "bran": {"Basic Type": "wheat bran"},
    "bratwurst": {"Basic Type": "pork", "Sub-Types": "sausage"},
    "breakfast bar": {"Basic Type": "bar"},
    "brownie": {"Basic Type": "dessert", "Sub-Types": "brownie"},
    "cake": {"Basic Type": "dessert", "Sub-Types": "cake"},
    "cannoli cream": {"Basic Type": "filling", "Sub-Types": "cannoli"},
    "cereal bar": {"Basic Type": "bar"},
    "cheesecake": {"Basic Type": "dessert", "Sub-Types": "cheesecake"},
    "chorizo": {"Basic Type": "pork", "Sub-Types": "sausage"},
    "clam juice": {"Basic Type": "juice", "Sub-Types": "clam"},
    "clover sprout": {"Basic Type": "sprout", "Sub-Types": "clover"},
    "club soda": {"Basic Type": "soda", "Sub-Types": "club"},
    "cooking wine": {"Basic Type": "wine", "Sub-Types": "cooking"},
    "cornish hen": {"Basic Type": "chicken", "Sub-Types": "cornish hen"},
    "crème fraiche": {"Basic Type": "cream", "Sub-Types": "fraiche"},
    "cupcake": {"Basic Type": "dessert", "Sub-Types": "cupcake"},
    "danish": {"Basic Type": "pastry", "Sub-Types": "danish"},
    "eggnog": {"Basic Type": "drink", "Sub-Types": "eggnog"},
    "farina": {"Basic Type": "cereal", "Sub-Types": "farina"},
    "frank": {"Basic Type": "beef", "Sub-Types": "frank"},
    "frisee": {"Basic Type": "lettuce", "Sub-Types": "frisee"},
    "fruit basket": {"Basic Type": "fruit", "Sub-Types": "variety"},
    "hog": {"Basic Type": "pork", "Sub-Types": "hog"},
    "honeydew": {"Basic Type": "melon", "Sub-Types": "honeydew"},
    "iced tea": {"Basic Type": "tea", "Sub-Types": "iced"},
    "jalepeno": {"Basic Type": "pepper", "Sub-Types": "jalepeno"},
    "juice slushie": {"Basic Type": "juice", "Sub-Types": "slushie"},
    "ketchup": {"Basic Type": "condiment", "Sub-Types": "ketchup"},
    "marmalade": {"Basic Type": "spread", "Sub-Types": "marmalade"},
    "marshmallow": {"Basic Type": "candy", "Sub-Types": "marshmallow"},
    "miso": {"Basic Type": "paste", "Sub-Types": "miso"},
    "mozzarella": {"Basic Type": "cheese", "Sub-Types": "mozzarella"},
    "nori": {"Basic Type": "seaweed", "Sub-Types": "nori"},
    "peppercorn": {"Basic Type": "spice", "Sub-Types": "peppercorn"},
    "pesto": {"Basic Type": "sauce", "Sub-Types": "pesto"},
    "pig feet": {"Basic Type": "pork", "Sub-Types": "feet"},
    "pita": {"Basic Type": "bread", "Sub-Types": "pita"},
    "potato yam": {"Basic Type": "potato", "Sub-Types": "yam"},
    "prosciutto": {"Basic Type": "pork", "Sub-Types": "prosciutto"},
    "pudding": {"Basic Type": "dessert", "Sub-Types": "pudding"},
    "romaine": {"Basic Type": "lettuce", "Sub-Types": "romaine"},
    "rotini": {"Basic Type": "pasta"},
    "sauerkraut": {"Basic Type": "condiment", "Sub-Types": "sauerkraut"},
    "seasoning tajin": {"Basic Type": "seasoning", "Sub-Types": "tajin"},
    "slush": {"Basic Type": "juice", "Sub-Types": "slushie"},
    "spam": {"Basic Type": "pork", "Sub-Types": "spam"},
    "spring mix": {"Basic Type": "lettuce", "Sub-Types": "spring mix"},
    "squash blossom": {"Basic Type": "squash", "Sub-Types": "blossom"},
    "sunflower": {"Basic Type": "seed", "Sub-Types": "sunflower"},
    "sweet potato": {"Basic Type": "potato", "Sub-Types": "sweet"},
    "tostada": {"Basic Type": "shell", "Sub-Types": "tostada"},
    "trail mix": {"Basic Type": "snack", "Sub-Types": "trail mix"},
    "turnip greens": {"Basic Type": "turnip", "Sub-Types": "greens"},
    "vegetable mix": {"Basic Type": "vegetable", "Sub-Types": "blend"},
    "whipped cream": {"Basic Type": "topping", "Sub-Types": "whipped cream"},
    "cantaloupe": {"Basic Type": "melon", "Sub-Types": "cantaloupe"},
    "blend": {"Basic Type": "vegetable", "Sub-Types": "blend"},
    "soy sauce": {"Basic Type": "condiment", "Sub-Types": "soy sauce"},
    "chicken breast": {"Basic Type": "chicken", "Shape": "breast"},
    "chicken tender": {"Basic Type": "chicken", "Shape": "cut"},
    "chicken nugget": {"Basic Type": "chicken", "Shape": "nugget"},
    "chocolate": {"Basic Type": "candy", "Sub-Types": "chocolate"},
    "chutney": {"Basic Type": "spread", "Sub-Types": "chutney"},
    "coleslaw": {"Basic Type": "salad", "Sub-Types": "coleslaw"},
    "corn nugget": {
        "Basic Type": "appetizer",
        "Sub-Types": "corn",
        "Processing": "battered",
    },
    "gel": {"Basic Type": "topping", "Sub-Types": "icing"},
    "ice cream cone": {"Basic Type": "cone", "Sub-Types": "ice cream"},
    "pan coating": {"Basic Type": "oil", "Sub-Types": "spray"},
    "paprika": {"Basic Type": "spice", "Sub-Types": "paprika"},
    "salad mix": {"Basic Type": "lettuce", "Sub-Types": "blend"},
    "toast": {"Basic Type": "bread", "Sub-Types": "toast"},
    "turmeric": {"Basic Type": "spice", "Sub-Types": "turmeric"},
    "orange blossom water": {"Basic Type": "water", "Sub-Types": "flavored"},
    "gyro meat": {"Basic Type": "beef", "Sub-Types": ["lamb", "gyro"]},
    "yogurt alternative": {
        "Basic Type": "yogurt",
        "Dietary Accommodation": "non-dairy",
    },
}

# Note: Do this separately since there is other tagging logic for all nut tags
for nut in NUTS:
    BASIC_TYPE_MAP[nut] = {"Basic Type": "nut", "Sub-Types": nut}
