"""Define sets of tags that have special rules for token mapping for CGFP pipeline"""

# More complicated conditional rules
# TODO: "blue" is a problem for colors and cheese » what about "white" for vegetables? "onion" but maybe we want this for other ones
# also white corn, etc.
# TODO: "whole weat" for pasta? ravioli?

### FLAVORS ###
# Tags to potentially be categorized as "flavored"
FLAVORS = {
    ## BEVERAGES & DRINKS ##
    # sweet drinks #
    "mocha",
    "hazelnut and cream",
    "hazelnut cream",
    "mocha latte",
    "arnold palmer",
    # sports drinks #
    "arctic blitz",
    "blue pomegranate",
    # spices #
    "vanilla",
    "cinnamon",
    # misc #
    "maple",
    ## CANDY ##
    "butterscotch",
    "coffee",
    "caramel",
    "m&m",
    "toffee",
    "milk",
    "moosetracks",
    ## BREAD ###
    "garlic",
    "chili",
    ## CHIPS ##
    "barbecue",
    "barbeque",
    "bbq",
    "sea salt",
    "flamin hot",
    "cheddar",
    "sour",
    "white cheddar",
    "sour cream",
    "variety",
    "extreme heat",
    "buffalo ranch",
    "queso",
    "cheddar and black pepper",
    "cheddar sour cream",
    "salt",
    "vinegar",
    "dill pickle",
    "jalapeno cheddar",
    ## CEREAL ##
    "brown sugar",
    "apple cinnamon",
    "cinnamon toast crunch",
    ## LEGUMES ##
    "seasoned",
    ## CHEESE ##
    "horseradish",
    "chives",
    "sauce",
    "beer",
    ## SEAFOOD ##
    "chipotle",
    "chive and cheddar",
    "parmesan basil",
    ## HERBS ##
    "mint",
    ## SNACKS ##
    "chocolate",
    "glacier freeze",
    ## TEA FLAVORS ##
    "orange and spice",
    "orange blossom",
    "orange carrot",
    "orange cherry grape",
    "orange citrus",
    "orange cream",
    "orange dulce",
    "orange guava passion",
    "orange mango",
    "orange medley",
    "peach ginger",
    ## FRUIT FLAVORS ##
    "guava pear",
    "guava strawberry",
    "mixed berry",
    "mixed fruit",
    "orange pineapple cherry",
    "orange pineapple crème",
    "paradise punch",
    "passion fruit pineapple",
    "passion orange",
    "passion orange guava",
    "peach hibiscus",
    "peach mango",
    "peach pineapple",
    "peach tea",
    "pear ginger",
    "yumberry pomegranate",
    "wildberry",
    "wild cherry",
    "strawberry and cream",
    "strawberry beet",
    "strawberry champagne",
    "strawberry chocolate",
    "strawberry cream",
    "strawberry crisp",
    "strawberry crème",
    "strawberry dragonfruit",
    "strawberry gelatin",
    "strawberry kiwi",
    "strawberry lemon",
    "strawberry lemonade",
    "strawberry mango",
    "strawberry oatmeal",
    "strawberry orange",
    "strawberry peach",
    "strawberry pomegranate",
    "strawberry raspberry",
    "strawberry rhubarb",
    "strawberry rosemary",
    "strawberry shortcake",
    "strawberry vanilla",
    "strawberry watermelon",
    "strawbery kiwi",
    "tangerine mango guava",
    "tangerine orange",
    "watermelon agave",
    "watermelon flavor",
    "watermelon passion fruit",
    "watermelon passionfruit",
    "wild berry",
    "white grape peach",
    "white grape cherry",
    "apple and ginger",
    "apple berry",
    "apple cherry",
    ## CANDY FLAVORS ##
    "sour apple",
    "sour ball",
    "star blast",
    ## MISC ##
    "herb and garlic",
    "honey barbecue",
    "honey barbecue glaze",
    "honey barbeque",
    "honey brown sugar",
    "mango chili lime",
    "mango hibiscus",
    "mango lime",
    "mango peach",
    "mango pineapple",
    "mango sticky rice",
    "mango strawberry pomegranate",
    "peanut butter chocolate butterscotch",
    "peanut butter crème",
    "wild white nacho",
    "spicy nacho",
    "spicy sichuan",
    "spicy sweet",
    "sweet and salty",
    "sweet orange",
    "sweet potato chocolate",
    "sweet potato chocolate chip",
    "sweet salty",
    "sweet spicy",
    "toasted almond",
    "toasted cinnamon",
    "tropical",
    "tropical banana",
    "tropical blend",
    "tropical citrus",
    "tropical fire",
    "tropical fruit",
    "tropical island",
    "tropical mango",
    "tropical orange",
    "tropical passion",
    "tropical punch",
    "tropical twist",
    "turmeric aloe",
    "vanilla almond",
    "vanilla cola",
    "vanilla wafer",
    "vanilla cream",
    "vanilla crème",
    "vanilla fig",
    "vanilla honey",
    "vanilla latte",
    "vanilla m&m",
    "vanilla milk chocolate",
    "vanilla strawberry",
    "vanilla caramel",
    "vanilla chocolate",
    "white chocolate chip",
    "sour cherry",
    "sour cherry lemon",
    "sour cream and onion",
    "sour heads",
    "sour patch",
    "sour patch kid",
    "sour patch kids",
    "sour raspberry",
    "sour watermelon",
    "apple peach",
    "apple smoked",
    "apple strawberry",
    "apple strawberry banana",
    "apple walnut",
    "apple whirls",
    "apple ginger",
    "amaretto",
    "sour cream & onion",
    "sour cream and cheddar",
    "sour cream and chive",
    "sour cream and herb",
    "sour cream cheddar",
    "sour cream chive",
    "sour cream herb",
    "sour cream onion",
    "sour swell",
    "spicy sweet chili",
    "spinach berry",
    "spinach feta",
    "strawberry frosted",
    "strawberry punch",
    "strawberry yogurt",
    "sweet and spicy",
    "sweet maui onion",
    "tangerine lemongrass",
    "tango",
    "teriyaki",
    "vanilla almond latte",
    "yogurt covered",
    "nacho jalapeno",
    "neapolitan",
    "oatmeal and crème",
    "oatmeal cinnamon raisin",
    "oatmeal cookie",
    "orange spice",
    "orange vanilla",
    "peach cobbler",
    "peppermint chip",
    "peppermint mocha",
    "pina colada",
    "pomegranate acai",
    "red velvet",
    "roasted garlic",
    "rocky road",
    "salt and vinegar",
    "salted caramel macchiato",
    "sea salt and vinegar",
    "sea salt caraway",
    "chocolate covered",
    "chocolate cream",
    "cookies and cream",
    "cool ranch",
    "dark chocolate",
    "fruit punch",
    "garden salsa",
    "garlic parmesan",
    "hawaiian barbecue",
    "hawaiian salted caramel",
    "jalapeno cheese",
    "jalapeno lime",
    "jalapeno nacho",
    "lemon cream",
    "lemon poppyseed",
    "mandarin ginseng",
    "mint chip brownie",
    "mint chocolate",
    "mocha almond",
    "mojito lime coconut",
    "ginger lemongrass",
    "ginger pineapple",
    "ginger turmeric",
    "confetti",
    "bourbon pecan",
    "caramel covered",
    "raspberry white chocolate",
    "almond sea salt",
    "almond toffee",
    "apple blueberry",
    "apple caramel",
    "apple cinnamon raisin",
    "apple cinnnamon",
    "apple mint",
    "banana chocolate",
    "banana chocolate chip",
    "banana walnut",
    "berry apple",
    "berry apple crisp",
    "berry blast",
    "berry blend",
    "berry blue",
    "berry lemon",
    "berry spinach",
    "birthday cake",
    "black cherry vanilla",
    "black raspberry",
    "blackberry blueberry",
    "blackberry sage",
    "blue raspberry",
    "blue raspberry lemon",
    "blue raspberry lemonade",
    "blue razzberry",
    "blueberry almond",
    "blueberry banana",
    "blueberry cashew vanilla",
    "blueberry cherry",
    "blueberry cranberry",
    "blueberry flavor",
    "blueberry frosted",
    "blueberry fruit",
    "blueberry lemon",
    "blueberry lemon poppyseed",
    "blueberry lemongrass",
    "blueberry pecan",
    "blueberry pistachio",
    "blueberry pomegranate",
    "broston cream",
    "brown sugar cinnamon",
    "butter pecan",
    "cappucino mocha",
    "caramel almond",
    "caramel almond and salt",
    "caramel almond nougat",
    "caramel almond sea salt",
    "caramel and vanilla",
    "caramel apple",
    "caramel cookie",
    "caramel crème",
    "caramel fudge pecan",
    "caramel honey vanilla",
    "caramel latte",
    "caramel macchiato",
    "caramel pecan",
    "caramel sea salt",
    "caramel vanilla",
    "cardamon cinnamon",
    "caribbean jerk",
    "carrot spice",
    "cherry almond",
    "cherry almond chip",
    "cherry and apple",
    "cherry flavor",
    "cherry garcia",
    "cherry guava",
    "cherry hibiscus",
    "cherry lime",
    "cherry pomegranate",
    "cherry raspberry",
    "cherry starfruit",
    "chile cherry",
    "chili citrus",
    "chipotle citrus",
    "chocolate almond",
    "chocolate banana",
    "chocolate berry",
    "chocolate blueberry",
    "chocolate cherry",
    "chocolate cherry cashew",
    "chocolate chip brownie",
    "chocolate chip peanut",
    "chocolate chip peanut butter",
    "chocolate chip pecan",
    "chocolate chip toffee",
    "chocolate chip walnut",
    "chocolate chocolate chip",
    "chocolate coffee",
    "chocolate hazelnut",
    "chocolate strawberry",
    "chocolate twist",
    "chocolate vanilla",
    "cinnamon apple",
    "cinnamon brown sugar",
    "cinnamon crisp",
    "cinnamon maple",
    "cinnamon oat",
    "cinnamon pecan",
    "cinnamon sugar",
    "cinnamon swirl",
    "cinnamon vanilla",
    "citrus energy",
    "cocoa cherry",
    "coconut almond",
    "coconut chocolate",
    "coconut cream pie",
    "coconut date ginger",
    "coconut mojito",
    "coconut vanilla",
    "coffee cinnamon",
    "coffee crunch",
    "cookie and cream",
    "cool blue",
    "cranberry almond",
    "cranberry apple",
    "cranberry grape",
    "cranberry grapefruit",
    "cranberry raspberry",
    "cranberry white chocolate",
    "dark bourbon caramel",
    "dark chocolate cherry",
    "dark chocolate mocha",
    "dark chocolate peanut butter",
    "double chocolate chip",
    "french vanilla",
    "frosted fudge",
    "fudge chip",
    "garlic chile",
    "golden crème",
    "green apple",
    "habanero lime",
    "honey almond",
    "honey almond maple",
    "honey and oat",
    "honey chocolate",
    "honey garlic",
    "honey oat",
    "honey pineapple",
    "horseradish pecan",
    "hot cherry",
    "hot nacho",
    "island fruit",
    "kiwi guava",
    "kiwi strawberry",
    "lavender melon",
    "lemon and honeysuckle",
    "lemon cayenne",
    "lemon cranberry",
    "lemon ginger",
    "lemon herb",
    "lemon lime",
    "lemon raspberry",
    "lemon white chocolate",
    "lime chili",
    "mango banana",
    "mango coconut",
    "maple bourbon pecan praline",
    "maple brown sugar",
    "maple cinnamon",
    "maple flavored",
    "maple pecan",
    "maple pecan sea salt",
    "mojito lime",
    "oat & honey",
    "oat chocolate chip",
    "orange cranberry",
    "orange pineapple",
    "orange sesame",
    "peach passion fruit",
    "peanut butter chip",
    "peanut butter chocolate",
    "peanut butter chocolate chip",
    "peanut butter chunk",
    "peanut butter crunch",
    "peanut butter dark chocolate",
    "pecan bourbon",
    "pepper raspberry",
    "pineapple mango",
    "pineapple orange",
    "pineapple orange guava",
    "pineapple orange mango",
    "pineapple peach",
    "pomegranate berry",
    "pomegranate blueberry",
    "pomegranate passion fruit",
    "pumpkin cranberry",
    "pumpkin pecan",
    "raspberry chamomile",
    "raspberry cherry",
    "raspberry ice",
    "raspberry lemon",
    "raspberry lime",
    "shrimp flavor",
    "smore and chocolate chip",
    "strawberry acai",
    "strawberry daquiri",
    "sweet potato maple",
    "tart cherry almond",
    "toasted marshmallow",
    "toffee almond",
    "toffee almond sea salt",
    "toffee covered",
    "toffee crunch",
    "vanilla buttercream",
    "vanilla fudge",
    "vanilla tangerine",
    "very berry",
    "watermelon rose",
    "white chocolate mocha",
    "wild berry hibiscus",
    "winterfresh",
    "almond apricot",
    "yogurt chip",
    "butter flavor",
    "lavender",
    "irish cream",
    "lime lemon",
    "smore",
    "sweet and smoky",
    "sweet and sour meatball",
    "sweet and sour sauce",
    "sweet mint",
    "sweet tea",
    "s'more",
    "smores",
    "pomegranate green",
    "silver ice",
    "sugar butter",
}

# Note: fruits are separated since there is separate logic for "fruit, blend"
FRUITS = {
    "orange",
    "guava",
    "apple",
    "berry",
    "lemon",
    "lime",
    "strawberry",
    "banana",
    "raspberry",
    "passion fruit",
    "pomegranate",
    "acai",
    "blueberry",
    "cherry",
    "peach",
    "pear",
    "watermelon",
    "watermelon strawberry",
    "coconut",
    "grapefruit",
    "mango",
    "blackberry",
    "black cherry",
    "pineapple",
    "tangerine",
}

ALL_FLAVORS = FLAVORS | FRUITS

# For these basic types, skip anything that is in the FLAVORS set
SKIP_FLAVORS = {
    "drink",
    "tea",
    "coffee",
    "candy",
    "condiment",
    "cereal",
    "oat",
    "bean",
    "ice cream",
    "cheesecake",
    "cracker",
    "dessert",
    "pastry",
    "cookie",
    "cake",
    "danish",
    "soda",
    "sports drink",
    "energy drink",
}

# For these basic types, tag anything that includes a FLAVORS tag as "flavored"
FLAVORED_BASIC_TYPES = {
    "bread",
    "yogurt",
    "french toast",
    "chip",
    "cranberry",
    "spread",
    "butter",
    "fruit ice",
    "popsicle",
    "mix",
}

# TODO: This ends up incorrect since it has two flavors
#  YOGURT ASSORTED RASPBERRY/PEACH L/F G/F	yogurt, rapsberry, peach, low fat	yogurt, rapsberry, flavored, low fat

### SHAPE ###

SKIP_SHAPE = {"chip", "candy"}

SHAPE_EXTRAS = {
    ## CANDY ##
    "truffle",
    "bar",
    "bark",
    ## CHIPS ##
    "tortilla",
    "triangle",
    "ridge",
    "round",
    "ridged",
    "lattice cut",
    "popped",
    "bowl",
    "scoop",
    "crisps",
}

### BLENDS/VARIETY/ETC ###
# These are tags that should be relabeled if there are multiple tags from the same category

# TODO: Maybe dynamically generate fruits and vegetables
VEGETABLES = {
    "produce",
    "artichoke",
    "carrot",
    "cauliflower",
    "pea",
    "celery",
    "broccoli",
    "pepper",
    "onion",
    "green bean",
    "wax bean",
    "edamame",
    "eggplant",
    "zucchini",
    "corn",
    "jalapeno",
    "potato",
    "red pepper",
    "romaine",
    "snap pea",
    "spinach",
    "sundried tomato",
    "tomatillo",
    "tomato",
    "tomato basil",
}

NUTS = {"almond", "cashew", "pecan", "pistachio", "hazelnut", "walnut", "macadamia", "kukui"}

CHEESE_TYPES = {
    "cheddar",
    "gruyere",
    "cheddar cheese",
    "monterey jack",
    "mozzarella",
    "jack",
    "provolone",
    "blue",
    "havarti",
    "gouda",
    "muenster",
    "white cheddar",
    "feta",
    "gorgonzola",
    "pepper jack",
    "parmesan",
    "swiss",
    "sottocenere",
    "van sormon",
    "tomme de hood",
    "asiago",
    "fontina",
    "ciliegine",
    "baby caprino",
    "barricato al pepe",
    "piemontese",
    "cotjia",
    "halloumi",
    "chevre",
    "chihuahua",
    "port salut",
    "deep ellum blue",
    "cotija",
    "colby",
    "burrata",
    "colby jack",
    "ricotta",
    "brie",
    "wensleydale",
    "romano pecorino",
    "bucheron",
    "caciotta",
    "manchego",
    "cheddar jack",
    "american",
    "jarlsberg",
    "mascarpone",
    "menonina",
    "menonita",
    "asadero",
    "birdville reserve",
    "botalon",
    "taleggio",
}

MELON_TYPES = {"cantaloupe", "honeydew", "watermelon", "galia", "hami", "crenshaw", "malichita"}

SUBTYPE_REPLACEMENT_MAP = {
    "fruit": "fruit",
    "cheese": "blend",
    "vegetable": "blend",
    "melon": "variety",
}

### MISC ###
CHOCOLATE = {"dark chocolate", "chocolate covered"}

CORN_CERAL = {
    "frosted corn flakes",
    "frosted flake",
    "frosted flakes",
    "honey nut chex",
    "trix",
    "froot loops",
    "chex",
    "cocoa puffs",
    "kix",
    "corn chex",
    "corn pops",
    "corn pop",
    "corn puff",
    "corn flakes",
    "purple flake",
    "purple flakes",
}

RICE_CEREAL = {"special k", "cocoa krispies", "rice chex", "rice krispies", "crisp rice", "rice crispy"}

WHEAT_CEREAL = {
    "frosted mini spooner",
    "frosted mini spooners",
    "frosted mini wheat",
    "frosted mini wheats",
    "frosted spooners",
    "frosted wheat",
    "frosted wheats",
    "fruit whirls",
    "kashi",
    "mini spooners",
    "mini spooner",
    "wheat bran flakes",
    "wheat frosted",
    "wheaties",
    "shredded wheat",
    "total",
}

OAT_CEREAL = {
    "fruity cheerios",
    "cheerios",
    "honey nut cheerios",
    "honey scooters",
    "lucky charms",
    "multigrain o",
    "multigrain oats",
    "toasted oats",
    "toasted white chocolate",
    "toasty o",
}

FRUIT_SNACKS = {
    "fruit roll up",
    "fruit roll-up",
    "fruit rolls",
    "fruit rollup",
    "fruit snack",
    "gusher",
}
