"""Defines a mapping dictionary for typos and inconsistencies in CGFP data pipeline"""

TOKEN_MAP_DICT = {
    ## TYPOS ##
    "talpia": "tilapia",
    "talapia": "tilapia",
    "omlete": "omelette",
    "omelete": "omelette",
    "grapefuit": "grapefruit",
    "cheedar": "cheddar",
    "carribean": "caribbean",
    "cardamon": "cardamom",
    "gerkin": "gherkin",
    "rapsberry": "raspberry",
    "granualted": "granulated",
    "furikaki": "furikake",
    "fettuccini": "fettuccine",
    "fettucine": "fettuccine",
    "fettucini": "fettuccine",
    "early gray": "earl grey",
    "whole grain rich  rich": "whole grain rich",
    "orchiette": "orecchiette",
    "campanelli": "campanelle",
    "unsweeted": "unsweetened",
    "peeled & deveined": "peeled and deveined",
    "peeled & devined": "peeled and deveined",
    "mangu": "mango",
    "siced": "sliced",
    "bicsuit": "biscuit",
    "brussel": "brussels sprout",
    "brussel spout": "brussels sprout",
    "brussel sprout": "brussels sprout",
    "bulghur": "bulgur",
    "bulgar": "bulgur",
    "bulgar wheat": "bulgur",
    "cabbabe": "cabbage",
    "collard": "collard greens",
    "collard green": "collard greens",
    "freekah": "freekeh",
    "grean pea": "green pea",
    "grean bean": "green bean",
    "green brean": "green bean",
    "grit": "grits",
    "jicima": "jicama",
    "lemon grass": "lemongrass",
    "onio": "onion",
    "pummelo": "pomelo",
    "rasberry": "raspberry",
    "shelll": "shell",
    "tamato": "tomato",
    "1 island": "thousand island",
    "alfafa": "alfalfa",
    "brocolini": "broccolini",
    "code": "cod",
    "berry lemonage": "berry lemonade",
    "gryo meat": "gyro meat",
    "patry": "pastry",
    "sweetner": "sweetener",
    "tat soi": "tatsoi",
    "tostado shell": "tostada",
    "chery": "cherry",
    "grean": "green",
    "green chili": "green chile",
    "guajillo chili": "guajillo chile",
    "habenero": "habanero",
    "hambuger": "hamburger",
    "harvarti": "havarti",
    "honey mustard dijon": "honey mustard",
    "iceburg": "iceberg",
    "jonogold": "jonagold",
    "marianra": "marinara",
    "mayonaise": "mayonnaise",
    "mayonaisse": "mayonnaise",
    "mirepoux": "mirepoix",
    "monterey jark": "monterey jack",
    "montery jack": "monterey jack",
    "mozzerella": "mozzarella",
    "peperoncini": "pepperoncini",
    "peppercini": "pepperoncini",
    "powedered": "powdered",
    "raisin brain": "raisin bran",
    "reeses pieces": "reese's pieces",
    "sandwhich": "sandwich",
    "snickerdoogle": "snickerdoodle",
    "springle": "sprinkle",
    "sqare rib": "spare rib",
    "stawberry": "strawberry",
    "sun-dried": "sun dried",
    "tumeric": "turmeric",
    "yogurt alternertive": "yogurt alternative",
    "tobasco": "tabasco",
    "burrio": "burrito",
    "raddicchio": "radicchio",
    "chcolate": "chocolate",
    "decaffienated": "decaffeinated",
    "decaffinated": "decaffeinated",
    "decafienated": "decaffeinated",
    "habiscus": "hibiscus",
    ## INCONSISTENCIES ##
    "cheeks": "cheek",
    "cheez it": "cheez-it",
    "cheez-its": "cheez-it",
    "skin-on": "skin on",
    "carrots": "carrot",
    "gluten-free": "gluten free",
    "tail-on": "tail on",
    "tail-off": "tail off",
    "sugar-free": "sugar free",
    "fillet": "filet",
    "fat-free": "fat free",
    "rice crispies": "rice krispies",
    "bread crumb": "breadcrumb",
    "bread stick": "breadstick",
    "brussels sprouts": "brussels sprout",
    "bulgur wheat": "bulgur",
    "cranberries": "cranberry",
    "egg": "eggs",
    "heart of palm": "hearts of palm",
    "peppers": "pepper",
    "vegetables": "vegetable",
    "vetegable": "vegetable",
    "wheat bulgur": "bulgur",
    "yuca": "yucca",
    "beef steak": "beefsteak",
    "corn meal": "cornmeal",
    "cornstarch": "corn starch",
    "egg nog": "eggnog",
    "micro greens": "microgreen",
    "micro green": "microgreen",
    "pimiento": "pimento",
    "preserves": "preserve",
    "spring": "spring mix",
    "tostada shell": "tostada",
    "turnip green": "turnip greens",
    "additive": "additives",
    "chives": "chive",
    "corn puffs": "corn puff",
    "cornish game hen": "cornish hen",
    "cous cous": "couscous",
    "dougnut": "doughnut",
    "florets": "floret",
    "froot loop": "froot loops",
    "fruit loop": "froot loops",
    "fruit loops": "froot loops",
    "frito": "fritos",
    "grannysmith": "granny smith",
    "cocoa": "cocoa powder",
    "grapes": "grape",
    "entree": "entrée",
    "chili relleno": "chile relleno",
    "relleno chile": "chile relleno",
    "beverage": "drink",
    "hachiya": "persimmon",
    ## COOKED ##
    "pre-cooked": "cooked",
    "au jus": "cooked",
    "charbroiled": "cooked",
    "oil roasted": "cooked",
    "roast": "cooked",
    "autumn roasted": "cooked",
    "blanched": "cooked",
    "char-broiled": "cooked",
    "grill": "cooked",
    "oven fired": "cooked",
    "oven roasted": "cooked",
    "par baked": "cooked",
    "par-fried": "cooked",
    "honey roasted": "cooked",
    "par-baked": "cooked",
    "red pepper roasted": "cooked",
    "steamed": "cooked",
    "stewed": "cooked",
    "toasted": "cooked",
    "tortilla crusted": "cooked",
    ## NUT ##
    "nut and honey": "nut",
    "nut and seed": "nut",
    "nut cluster": "nut",
    ## RENAME ##
    "aprium": "pluot",
    "banana pepper": "pepper",
    "blood orange": "orange",
    "bluelake bean": "bean",
    "bouillon": "base",
    "cotton candy": "candy",
    "pig": "pork",
    "romano bean": "bean",
    "pigeon pea": "bean",
    "cracker meal": "breadcrumb",
    "hasu": "lotus root",
    "satsuma": "mandarin",
    "white rice": "rice",
    "half and half lemonade": "lemonade",
    ## CUT ##
    "sliced": "cut",
    "diced": "cut",
    "chopped": "cut",
    "wedge": "cut",
    "segment": "cut",
    "baby": "cut",
    "julienne": "cut",
    "julienned": "cut",
    "quartered": "cut",
    "quarter": "cut",
    "cubed": "cut",
    "cube": "cut",
    "chunk": "cut",
    "trimmed": "cut",
    "half": "cut",
    "halved": "cut",
    "halves": "cut",
    "spear": "cut",
    "crinkle cut": "cut",
    "florette": "cut",
    "filet": "cut",
    "portion": "cut",
    "rectangle": "cut",
    "coin": "cut",
    "square": "cut",
    "strip": "cut",
    "stripe": "cut",
    "tender": "cut",
    "airline breast": "cut",
    "deli sliced": "cut",
    "fillet diced": "cut",
    "ham sliced": "cut",
    "minced": "cut",
    "portioned": "cut",
    "sliver": "cut",
    "steel cut": "cut",
    "coin cut": "cut",
    ## WHOLE GRAIN ##
    "whole wheat": "whole grain rich",
    "whole grain": "whole grain rich",
    "white whole wheat": "whole grain rich",
    "honey wheat ranch": "whole grain rich",
    ## COOKED ##
    "baked": "cooked",
    "fried": "cooked",
    "roasted": "cooked",
    "parboiled": "cooked",
    "parcooked": "cooked",
    "broiled": "cooked",
    "parbaked": "cooked",
    "parfried": "cooked",
    "blackened": "cooked",
    "flame broiled": "cooked",
    "flamebroiled": "cooked",
    ## FLAVORED ##
    "clear blue raspberry": "flavored",
    "frost riptide": "flavored",
    "garden salsa": "flavored",
    "garden vegetable": "flavored",
    "garlic parmesan": "flavored",
    "garlic roasted and herb": "flavored",
    "ginger lemon": "flavored",
    "ginger peach": "flavored",
    "glacier cherry": "flavored",
    "glacier freeze": "flavored",
    "glacier ice": "flavored",
    "blueberry vanilla": "flavored",
    ## PROCESSING ##
    "condensed": "concentrate",
    "crusted": "breaded",
    "powdered": "powder",
    ## PACKAGING ##
    "bag": "ss",
    "kcup": "ss",
    "in jar": "jarred",
    "packet": "ss",
    "pouch": "ss",
    ## IN JUICE, ETC ##
    "in pear juice": "in juice",
    "in fruit juice": "in juice",
    "in juice concentrate": "in juice",
    "in olive oil": "in oil",
    "in heavy syrup": "in syrup",
    "in tomato sauce": "in sauce",
    "in vinaigrette": "in vinegar",
    "light syrup": "in light syrup",
    ## SMOKED ##
    "pecanwood smoked": "smoked",
    "hickory smoke": "smoked",
    "hickory smoked": "smoked",
    "smoke": "smoked",
    "hadwood smoked": "smoked",
    "hardwood smoked": "smoked",
    "mesquite smoked": "smoked",
    "applewood smoked": "smoked",
    "mesquite smoke": "smoked",
    # "mesquite": "cooked",  # TODO: what should we do with this?
    ## MIXED VEGGIES ##
    "vegetable cup": "vegetable",
    ## PASTA TYPES ##
    "penne rigate": "pasta",
    "rigatoni": "pasta",
    ## PASTRIES ##
    "sweet roll": "pastry",
    ## DIETARY CONCERN ##
    "less sodium": "low sodium",
    "less salt": "low sodium",
    ## CAFFEINE ##
    "decaf": "decaffeinated",
    ## CHEESE ##
    "mozzarella ciliegini": "mozzarella",
    "mozzarella ovalini": "mozzarella",
    "mozzarella ovoline": "mozzarella",
    ## SUB-TYPE INCONSISTENCIES ##
    "ancho chile powder": "ancho chile",
    "apple oatmeal": "oatmeal",
    "apple pie": "pie",
    "blackeye pea": "pea",
    "cheese filled": "cheese",
    "chicken fried": "fried",
    "chili ancho": "ancho chile",
    "cracker sandwich": "cracker",
    "earl gray": "earl grey",
    "egg white": "egg",
    "french catalina": "catalina",
    "french cut": "cut",
    "french honey": "french",
    "french red": "french",
    "fresco rancher": "queso fresco",
    "garlic pepper steak": "garlic pepper",
    "green jasmine": "green",
    "green lotus blossom": "green",
    "hanging tender": "tender",
    "ham hock": "ham",
    "hanger": "hanger steak",
    "hard cooked": "hard boiled",
    "hard-boiled": "hard boiled",
    "hardboiled": "hard boiled",
    "harissa red chili": "harissa",
    "herbal peppermint": "herbal",
    "holland gouda": "gouda",
    "honeycomb tripe": "tripe",
    "in shell": "shell on",
    "kaffir": "kaffir leaf",
    "kaffir lime leaf": "kaffir leaf",
    "long grain and wild rice": "long grain and wild",
    "wild and long grain": "long grain and wild",
    "low-fat": "low fat",
    "lowfat": "low fat",
    "luck charm": "lucky charms",
    "lucky charm": "lucky charms",
    "maraschino cherry": "maraschino",
    "1000 island": "thousand island",
    "multi-grain": "multigrain",
    "nectar agave": "syrup",
    "no additive": "no additives",
    "non dairy": "non-dairy",
    "non fat": "nonfat",
    "non-fat": "nonfat",
    "okinawan sweet": "sweet",
    "onions": "onion",
    "orange peko": "black",  # tea
    "orange pekoe": "black",
    "orange pineable": "orange pineapple",
    "osmolite": "osmolyte",
    "parmesan american grana": "blend",
    "parmesan herb crusted": "cheese",
    "sauerkrat": "sauerkraut",
    "yelow": "yellow",
    "tostado": "tostada",
    "tortila": "tortilla",
    "toritlla": "tortilla",
    "terragon": "tarragon",
    "sugarsnap": "sugar snap",
    "skiness": "skinless",
    "sesame giner": "sesame ginger",
    "seckle": "seckel",
    "portabello": "portobello",
    "portabella": "portobello",
    "poppyseed": "poppy seed",
    "pomegrante": "pomegranate",
    "pineaple": "pineapple",
    "pepperjack": "pepper jack",
    "mcintosh": "macintosh",
    "kimchee": "kimchi",
    "jalepeno": "jalapeno",
    "insant": "instant",
    "hotdog": "hot dog",
    "drumstrick": "drumstick",
    "demi-glace": "demi glace",
    "cinnamon taost crunch": "cinnamon toast crunch",
    "canteloupe": "cantaloupe",
    "bone in": "bone-in",
    "bones": "bone",
    "amagaki": "persimmon",
    "yellow fin": "yellowfin",
    "worcestershire sauce": "worcestershire",
    "worchestershire": "worcestershire",
    "worstersher": "worcestershire",
    "with dressing": "dressing",
    "with canola oil": "in oil",
    "pepporoni": "pepperoni",
    "protabello": "portobello",
    "sopaipilla": "sopapilla",
    "rib back": "rib",
    "ribs": "rib",
    "spare rib": "rib",
    "straight neck": "straightneck",
    "striaghtneck": "straightneck",
    "sugar bee": "sugarbee",
    "sweet & sour": "sweet and sour",
    "sweet & spicy": "sweet and spicy",
    "sweet paprika": "paprika",
    "tiramisu bar": "cake",
    "white chocolate": "chocolate",
    "white grape": "grape",
    "white chocolate sauce": "chocolate sauce",
    "Cuban": "cuban",
    "challa": "challah",
    "ceasar": "caesar",
    "canellini": "cannellini",
    "breat": "breast",
    "breafkast": "breakfast",
    "bluberry": "blueberry",
    "bleu cheese": "blue cheese",
    "black-eyed": "black-eyed pea",
    "black eyed pea": "black-eyed pea",
    "balsamic vinagrette": "balsamic vinaigrette",
    "anise": "star anise",
    "ancho chile": "ancho",
    "ancho chili": "ancho",
    "ancho chipotle": "ancho",
    "all spice": "allspice",
    "crumbled": "crumble",
    "feta cheese": "feta",
    "jar": "jarred",
    "jerkey": "jerky",
    "kettled cooked": "kettle cooked",
    "salted almond": "almond",
    "salted peanut": "peanut",
    "freshly baked": "freshly prepared",
    "swiss chocolate": "hot chocolate",
    "quick": "instant",
    "adobo sauce": "in sauce",
    "with icing": "icing",
    "with ranch": "dressing",
    "raspberry cream cheese": "cream cheese",
    "salted dark chocolate": "chocolate",
    "raspberry cheese": "cheese",
    "snicker": "snickers",
    "basil": "herb",
    "sage": "herb",
    "lemonade cocktail": "cocktail",
    "orange pomegranate cocktail": "cocktail",
    "maple almond butter": "almond butter",
    "orange cocktail": "cocktail",
    "fajita": "seasoned",
    "garlic and herb": "seasoned",
    "garlic cheddar": "seasoned",
    "garlic herb": "seasoned",
    "garlic pesto": "seasoned",
    "mesquite": "seasoned",
    "onion garlic herb": "seasoned",
    "parmesan garlic herb": "seasoned",
    "salisbury": "seasoned",
    "salisbury steak": "seasoned",
    "salt and pepper": "seasoned",
    "salted almond butter": "seasoned",
    "spice": "seasoned",
    "spinach herb": "seasoned",
    "assorted": "variety",
    "in pineapple juice": "in juice",
    "in sunflower oil": "in oil",
    "in balsamic vinegar": "in vinegar",
}
