config:
  smoke_test: false
input_data:
  # input_file: "CONFIDENTIAL_CGFP bulk data_073123.xlsx"
  input_file: "PPS_new_dataset_formatted.csv"
output_data:
  misc_file: "misc.csv"
  clean_file_prefix: "clean_"