# TODO: Maybe set up Paths, etc for this
config:
  smoke_test: false
data:
  text_field: "Product Type"
  data_dir: "/net/projects/cgfp/data/clean/"
  train_filename: "new_clean_CONFIDENTIAL_CGFP_bulk_data_073123.csv"
  eval_filename: "combined_eval_set.csv"
model:
  model_name: "distilbert-base-uncased"
  classification: "mlp" # Choices: "mlp", "linear"
  loss: "cross_entropy" # Choices: "cross_entropy", "focal"
  save_best: true
  train_attention: false # TODO: do I actually need this? Freezes MLPs and only trains attention
  freeze_model: false # TODO: clarify args — freezes everythinge except classification heads
training:
  lr: 0.001
  epochs: 80
  train_batch_size: 32
  eval_batch_size: 64