TOKEN_MAP_DICT = {
    "whole grain rich  rich": "whole grain rich",
    "gluten-free": "gluten free",
}

TAGS = {
    "Beverages": {
        "Flavor/Cut": {"flavored"},
        "Shape": {"thickened", "concentrate"},
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": {"low sodium", "reduced sugar"},
        "Additives": {"no additives"},
        "Dietary Accommodation": {"gluten free", "non-dariy", "vegan"},
        "Frozen": {"frozen/iced"},
        "Packaging": {"ss"},
        "Commodity": {"commodity"},
    },
    "Bread, Grains & Legumes": {
        "Flavor/Cut": {"flavored"},
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": {"bleached", "dried", "halved"},
        "Cooked/Cleaned": {"oil roasted", "parbaked", "roasted"},
        "WG/WGR": {"whole grain rich"},
        "Dietary Concern": {"salted", "unsalted"},
        "Additives": {"no additives"},
        "Dietary Accommodation": {"gluten free"},
        "Frozen": {"frozen"},
        "Packaging": {"ss"},
        "Commodity": {"commodity"},
    },
    "Cheese": {
        "Flavor/Cut": {"flavored"},
        "Shape": {"stick", "string"},
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": {
            "dried",
            "grated",
            "sauce",
            "shaved",
            "shredded",
            "sliced",
            "whipped",
        },
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": {"2%", "reduced fat", "reduced sodium"},
        "Additives": {"no additives"},
        "Dietary Accommodation": set(),
        "Frozen": {"frozen"},
        "Packaging": {"ss"},
        "Commodity": {"commodity"},
    },
    "Condiments & Snacks": {
        "Flavor/Cut": {"flavored"},
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": {"diced", "dried", "in juice", "sliced"},
        "Cooked/Cleaned": {"baked", "cooked", "fried", "kettle cooked"},
        "WG/WGR": {"whole grain rich"},
        "Dietary Concern": {"low sodium", "no sugar added", "reduced fat"},
        "Additives": {"no additives", "additives"},
        "Dietary Accommodation": {"gluten free", "kosher", "vegan", "vegetarian"},
        "Frozen": {"frozen"},
        "Packaging": {"ss", "canned"},
        "Commodity": {"commodity"},
    },
    "Meals": {
        "Flavor/Cut": set(),
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": {"breaded", "condensed", "dehydrated"},
        "Cooked/Cleaned": {"fried", "roasted"},
        "WG/WGR": {"whole grain rich"},
        "Dietary Concern": {"reduced fat", "reduced sodium"},
        "Additives": {"no additives"},
        "Dietary Accommodation": {"halal", "kosher", "vegan", "vegetarian"},
        "Frozen": set(),
        "Packaging": {"canned", "ss"},
        "Commodity": {"commodity"},
    },
    "Meat": {
        "Flavor/Cut": {
            "brisket",
            "breast",
            "loin",
            "shank",
            "skirt",
            "steak",
            "short rib",
            "t-bone",
            "thigh",
            "whole",
            "wing",
        },
        "Shape": {
            "bacon",
            "chunk",
            "diced",
            "fillet",
            "ground",
            "ham",
            "hot dog",
            "jerky",
            "link",
            "meatball",
            "nugget",
            "pepperoni",
            "patty",
            "popcorn",
            "portion",
            "pulled",
            "salami",
            "strip",
            "taco meat",
            "tender",
        },
        "Skin": set(),
        "Seed/Bone": {"bone-in"},
        "Processing": {
            "au jus",
            "battered",
            "breaded",
            "corned",
            "seasoned",
            "shredded",
        },
        "Cooked/Cleaned": {"charbroiled", "cooked", "fried", "roasted"},
        "WG/WGR": set(),
        "Dietary Concern": {"low sodium"},
        "Additives": {"no additives"},
        "Dietary Accommodation": {"gluten free", "halal", "kosher"},
        "Frozen": {"frozen"},
        "Packaging": set(),
        "Commodity": {"commodity"},
    },
    "Milk": {
        "Flavor/Cut": {"flavored"},
        "Shape": {"thickened"},
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": {"lactose free"},
        "Frozen": set(),
        "Packaging": {"bag", "ss"},
        "Commodity": {"commodity"},
    },
    "Milk & Dairy": {
        "Flavor/Cut": set(),
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": {"condensed", "evaporated", "powdered"},
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": {"no additives"},
        "Dietary Accommodation": {"lactose free"},
        "Frozen": {"frozen"},
        "Packaging": {"ss"},
        "Commodity": {"commodity"},
    },
    "Produce": {
        "Flavor/Cut": {"blend", "variety", "salad mix"},
        "Shape": {
            "baby",
            "bite",
            "cob",
            "coin",
            "florette",
            "segment",
            "stick",
            "stripe",
            "wedge",
        },
        "Skin": set(),
        "Seed/Bone": {"pitted", "seedless"},
        "Processing": {
            "chopped",
            "cupped",
            "halved",
            "shredded",
            "in juice",
            "in water",
        },
        "Cooked/Cleaned": {"cleaned"},
        "WG/WGR": set(),
        "Dietary Concern": {"low sodium", "low sugar"},
        "Additives": {"no additives"},
        "Dietary Accommodation": set(),
        "Frozen": {"frozen"},
        "Packaging": {"jarred", "canned", "ss"},
        "Commodity": {"commodity"},
    },
    "Seafood": {
        "Flavor/Cut": {"loin", "meat", "shank", "steak"},
        "Shape": {
            "cake",
            "chunk",
            "fillet",
            "flake",
            "nugget",
            "patty",
            "popcorn",
            "popper",
            "portion",
            "square",
            "stick",
            "surimi",
            "rectangle",
            "ring",
            "wedge",
            "whole",
        },
        "Skin": set(),
        "Seed/Bone": {"bone-in"},
        "Processing": {
            "chopped",
            "crusted",
            "breaded",
            "battered",
            "dried",
            "in water",
            "in oil",
            "puree",
        },
        "Cooked/Cleaned": {"smoked"},
        "WG/WGR": set(),
        "Dietary Concern": {"low sodium"},
        "Additives": {"no additives"},
        "Dietary Accommodation": set(),
        "Frozen": {"frozen"},
        "Packaging": set(),
        "Commodity": {"commodity"},
    },
    "Non-Food": {
        "Bread, Grains & Legumes": set(),
        "Flavor/Cut": set(),
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
}

ADDED_TAGS = {
    "Beverages": {
        "Flavor/Cut": set(),
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": {"frozen", "iced"},
        "Packaging": set(),
        "Commodity": set(),
    },
    "Bread, Grains & Legumes": {
        "Flavor/Cut": {"sliced"},
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": {"raw", "cooked", "parboiled", "baked"},
        "WG/WGR": set(),
        "Dietary Concern": {"low sodium", "low carb", "low sugar", "reduced fat"},
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": {"canned"},
        "Commodity": set(),
    },
    "Cheese": {
        "Flavor/Cut": {"shredded"},
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
    "Condiments & Snacks": {
        "Flavor/Cut": set(),
        "Shape": {"powder"},
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": {"roasted"},
        "WG/WGR": set(),
        "Dietary Concern": {
            "low fat",
            "less sodium",
            "less salt",
            "low calorie",
            "low carb",
            "no sugar",
            "reduced sodium",
            "sugar free",
        },
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": {"jarred"},
        "Commodity": set(),
    },
    "Meals": {
        "Flavor/Cut": set(),
        "Shape": {"patty"},
        "Skin": {"skin on"},
        "Seed/Bone": {"boneless"},
        "Processing": set(),
        "Cooked/Cleaned": {
            "cooked",
            "blanched",
            "raw",
            "baked",
            "parcooked",
            "parfried",
        },
        "WG/WGR": set(),
        "Dietary Concern": {"low sodium"},
        "Additives": set(),
        "Dietary Accommodation": {"gluten free"},
        "Frozen": set(),
        "Packaging": {"canned"},
        "Commodity": set(),
    },
    "Meat": {
        "Flavor/Cut": set(),
        "Shape": {"sliced"},
        "Skin": {"skinless"},
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": {"raw", "roast", "smoked"},
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": {"ss"},
        "Commodity": set(),
    },
    "Milk": {
        "Flavor/Cut": set(),
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
    "Milk & Dairy": {
        # TODO: maybe these should be in shape instead?
        "Flavor/Cut": {"shredded", "sliced", "flavored", "grated"},
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": {
            "nonfat",
            "low fat",
            "fat free",
            "light",
            "low sodium",
            "low sugar",
            "no sugar added",
            "reduced fat",
            "reduced sodium",
        },
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": {"canned"},
        "Commodity": set(),
    },
    "Produce": {
        "Flavor/Cut": {"cut", "diced", "sliced"},
        "Shape": {"large"},
        "Skin": {"skin-on"},
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": {"roasted"},
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
    "Seafood": {
        "Flavor/Cut": set(),
        "Shape": {"filet", "cubed"},
        "Skin": {"skinless"},
        "Seed/Bone": {"boneless"},
        "Processing": set(),
        "Cooked/Cleaned": {"raw", "cooked"},
        "WG/WGR": {"whole grain rich"},
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
    "Non-Food": {
        "Bread, Grains & Legumes": set(),
        "Flavor/Cut": set(),
        "Shape": set(),
        "Skin": set(),
        "Seed/Bone": set(),
        "Processing": set(),
        "Cooked/Cleaned": set(),
        "WG/WGR": set(),
        "Dietary Concern": set(),
        "Additives": set(),
        "Dietary Accommodation": set(),
        "Frozen": set(),
        "Packaging": set(),
        "Commodity": set(),
    },
}
